import { Assistant } from "next/font/google";
import "./globals.css";


const AssistantFont = Assistant({
  weight:["200","300","400","500","600","700","800"],
  subsets:["latin"],
  display:"swap"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${AssistantFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
